source 'https://rubygems.org'

gem 'page-object'
gem 'selenium-webdriver'
gem 'watir-wait_with_refresh'
gem 'rspec'
gem 'faker'
gem 'pry'
gem 'pry-nav'
gem 'colored'
gem 'require_all'
gem 'activesupport', '~> 4.0.1'
